### ISSUE TITLE
aten_index_put doesn't support 1-D tensor

### ISSUE THREAD

**Issue by titaiwangms** [microsoft/onnxscript#1212]
```
_ TestOnnxModelOutputConsistency_opset_version_18_model_type_TorchModelType.TORCH_NN_MODULECPU.test_output_match_index_add_cpu_int32 (inputs='(tensor([0], dtype=torch.int32), 0, tensor([0]), tensor([-5], dtype=torch.int32))', kwargs="{'alpha': 0}", opset=18, sample_num=4) _
[gw3] linux -- Python 3.11.5 /home/titaiwang/anaconda3/envs/pytorch-dev/bin/python
Traceback (most recent call last):
  File "/home/titaiwang/anaconda3/envs/pytorch-dev/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/home/titaiwang/anaconda3/envs/pytorch-dev/lib/python3.11/unittest/case.py", line 538, in subTest
    yield
  File "/home/titaiwang/pytorch/test/onnx/test_fx_registry_op_consistency.py", line 748, in _run_test_output_match
    _compare_onnx_and_torch_exported_program(
  File "/home/titaiwang/pytorch/test/onnx/test_fx_registry_op_consistency.py", line 665, in _compare_onnx_and_torch_exported_program
    onnx_outputs = onnx_exported_program(*input_args, **input_kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/titaiwang/pytorch/torch/onnx/_internal/exporter.py", line 729, in __call__
    return ort_session.run(None, onnxruntime_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/titaiwang/anaconda3/envs/pytorch-dev/lib/python3.11/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 220, in run
    return self._sess.run(output_names, input_feed, run_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running Gather node. Name:'_inline_aten_index_putn4' Status Message: indices element out of data bounds, idx=1 must be within the inclusive range [-1,0]
```

It seems op.Gather assumes input tensor to be at least 2d.

https://github.com/microsoft/onnxscript/blob/9fab64370061cd349aff1354548642e7b72158b1/onnxscript/function_libs/torch_lib/ops/core.py#L4028-L4056

**Comment by justinchuby** [comment]
Gather seems to support rank>=1 tensors. https://onnx.ai/onnx/operators/onnx__Gather.html  Should we raise an issue in ORT?

**Comment by titaiwangms** [comment]
I mean in line 4039, we would be out of bound if the input is not 2d.

**Comment by justinchuby** [comment]
I see, thanks!

**Comment by titaiwangms** [comment]
Fixed by https://github.com/microsoft/onnxscript/pull/1298
