### ISSUE TITLE
pattern rewrite error: Unexpected onnxscript value type '<class 'onnxscript.ir.Value'>'

### ISSUE THREAD

**Issue by happyme531** [microsoft/onnxscript#1886]
I want to replace all opset18 ScatterElements into their opset16 version. So I wrote this script:

```python
from onnxscript.rewriter import pattern
import onnx.numpy_helper as onh
import onnx
import onnxscript
from onnxscript import opset16

def ScatterElements18(op, input, indices, updates, axis ,reduction):
    return op.ScatterElements(input, indices, updates, axis=axis, reduction=reduction)

def ScatterElements16(op, input, indices, updates, axis ,reduction):
    return opset16.ScatterElements(input, indices, updates, axis=axis, reduction=reduction)

rewrite_scatterElements18 = pattern.RewriteRule(ScatterElements18, ScatterElements16)
rewrite_rule_set = pattern.RewriteRuleSet([rewrite_scatterElements18],commute=True)
model = onnx.load("RWKV-x060-World-1B6-v2.1-20240328-ctx4096.onnx", load_external_data=False)
replaced_model = onnxscript.rewriter.rewrite(
    model,
    pattern_rewrite_rules=rewrite_rule_set
)
onnx.save(replaced_model, "RWKV-x060-World-1B6-v2.1-20240328-ctx4096.onnx")
```

But it is not working:
```
> python ./downgrade_ops.py                                                        
Traceback (most recent call last):
  File "./downgrade_ops.py", line 16, in <module>
    replaced_model = onnxscript.rewriter.rewrite(
  File "/home/zt/.conda/envs/rknn/lib/python3.8/site-packages/onnxscript/rewriter/__init__.py", line 48, in rewrite
    count = pattern_rewrite_rules.apply_to_model(model_ir)
  File "/home/zt/.conda/envs/rknn/lib/python3.8/site-packages/onnxscript/rewriter/pattern.py", line 1380, in apply_to_model
    count = self._apply_to_graph_or_function(model, model.graph, verbose=verbose)
  File "/home/zt/.conda/envs/rknn/lib/python3.8/site-packages/onnxscript/rewriter/pattern.py", line 1358, in _apply_to_graph_or_function
    delta = rule.try_rewrite(model, graph_or_function, node, verbose=verbose)
  File "/home/zt/.conda/envs/rknn/lib/python3.8/site-packages/onnxscript/rewriter/pattern.py", line 1234, in try_rewrite
    replacement_subgraph = self._replacement_pattern.get_replacement(match)
  File "/home/zt/.conda/envs/rknn/lib/python3.8/site-packages/onnxscript/rewriter/pattern.py", line 852, in get_replacement
    new_outputs = self._function(context, **match.bindings)
  File "./downgrade_ops.py", line 11, in ScatterElements16
    return opset16.ScatterElements(input, indices, updates, axis=1, reduction=reduction)
  File "/home/zt/.conda/envs/rknn/lib/python3.8/site-packages/onnxscript/onnx_opset/_impl/opset16.py", line 1086, in ScatterElements
    return op(
  File "/home/zt/.conda/envs/rknn/lib/python3.8/site-packages/onnxscript/values.py", line 301, in __call__
    return evaluator.default().eval(schema, args, kwargs)
  File "/home/zt/.conda/envs/rknn/lib/python3.8/site-packages/onnxscript/evaluator.py", line 194, in eval
    outputs = self._eval(schema, inputs, attributes, closure)
  File "/home/zt/.conda/envs/rknn/lib/python3.8/site-packages/onnxscript/evaluator.py", line 512, in _eval
    return _call_ort(schema, inputs, attributes, closure)
  File "/home/zt/.conda/envs/rknn/lib/python3.8/site-packages/onnxscript/evaluator.py", line 473, in _call_ort
    model, session_run_input, inputs = _prepare_model_and_inputs_for_eager(
  File "/home/zt/.conda/envs/rknn/lib/python3.8/site-packages/onnxscript/evaluator.py", line 413, in _prepare_model_and_inputs_for_eager
    args = [_onnxscript_to_numpy_value(x) for x in args]
  File "/home/zt/.conda/envs/rknn/lib/python3.8/site-packages/onnxscript/evaluator.py", line 413, in <listcomp>
    args = [_onnxscript_to_numpy_value(x) for x in args]
  File "/home/zt/.conda/envs/rknn/lib/python3.8/site-packages/onnxscript/evaluator.py", line 379, in _onnxscript_to_numpy_value
    raise TypeError(
TypeError: Unexpected onnxscript value type '<class 'onnxscript.ir.Value'>'.Valid value types are 'Tensor | list[Tensor] | None | np.ndarray | list[np.ndarray]'
```

Any solution or help?

**Comment by justinchuby** [comment]
Replace opset16 with op

**Comment by justinchuby** [comment]
Be sure to change the opset version in the model too
