### ISSUE TITLE
Runtime Error: Decorator script does not work dynamically compiled function

### ISSUE THREAD

**Issue by tuanle0910** [microsoft/onnxscript#1969]
Hi everyone, I get the Runtime Error when running the function below in Poetry environment with Python 3.11 and Pycharm IDE. I was able to run it successfully from Virtual Environment (the `.venv`). Can someone offer help on how to fix it?

```
import numpy as np
import onnx
import onnxruntime
import pandas as pd
from onnxscript import FLOAT
from onnxscript import opset20 as op

x = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])
y = np.array(x[len(x) - 3: len(x)], dtype=np.float32)
z = np.array(x[len(x)-8: len(x)-3], dtype=np.float32)

x_coef = np.array([1.1, 1.5, 1.7, 1.9, 1.2, 3.1, 4.5, 5.2, 8.5, 9.0, 11.0]
y_coef = np.array([8.5, 9.0, 11.0])
z_coef = np.array([5,7,9,9,10,11])

t1 = len(x)
t2 = len(y)
t3 = len(z)

const_term = 2.37698
h1 = 1.5689
h2 = 1.799

@script()
def conv(a1: FLOAT, a2: FLOAT, a3: FLOAT, a4: FLOAT, a5: FLOAT) -> FLOAT:
    const = op.Constant(value_float=const_term)
    # Define constants
    coeff1 = op.Constant(value_float=h1)
    coeff2 = op.Constant(value_float=h2)
    s = coeff1 * a1  + coeff2 * a2 - const

    for inx in range(t1):
        if a4 == x[inx]:
            s = s + x_coef[inx]
    for inx2 in range(t2):
        if a5 == y[inx2]:
            s = s + y_coef[inx2]
    for inx3 in range(t3):
        if a6 == z[inx3]:
            s = s + z_coef[inx3]
    
    return op.Exp(s)
```

**Error Message**
Traceback (most recent call last):
  File "[File_path]/lib/python3.11/site-packages/onnxscript/_internal/ast_utils.py", line 18, in get_src_and_ast
    src = inspect.getsource(func)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "[file_path]/.asdf/python/3.11.9/lib/python3.11/inspect.py", line 1258, in getsource
    lines, lnum = getsourcelines(object)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "[file_path]/.asdf/installs/python/3.11.9/lib/python3.11/inspect.py", line 1240, in getsourcelines
    lines, lnum = findsource(object)
                  ^^^^^^^^^^^^^^^^^^
  File "[file_path]/.asdf/installs/python/3.11.9/lib/python3.11/inspect.py", line 1077, in findsource
    raise OSError('could not get source code')
**OSError: could not get source code**

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 1, in <module>
  File "<input>", line 67, in [module_name]
  File "[path]/lib/python3.11/site-packages/onnxscript/main.py", line 82, in transform
    src, f_ast = ast_utils.get_src_and_ast(f)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[path]/lib/python3.11/site-packages/onnxscript/_internal/ast_utils.py", line 20, in get_src_and_ast
    raise RuntimeError(
**RuntimeError: Decorator script does not work on dynamically compiled function conv.**

**Comment by tuanle0910** [comment]
@justinchuby @gramalingam @xadupre @titaiwangms  Could either of you please help take a look at this problem?

**Comment by xadupre** [comment]
x, x_coef, ... appear to be global variables. That's not allowed. They should become inputs or constant declared in the function body.

**Comment by tuanle0910** [comment]
@xadupre Thank you very much for your quick reply. I tried both ways but the same error still appeared. I am not sure if the actual cause is because the @script() decorator was placed inside another function (e.g. `def far()`) ? The script above runs fine when it was placed outside of anything. However, I just check and even the given example here (https://onnxscript.ai/api/decorator.html) get the same error as above, so perhaps the actual cause was due to package version?

- onnx: 1.16.0
- onnxconverter-common: 1.13.0
- onnxmltools: 1.12.0
- onnxruntime: 1.16.3
- onnxscript: 0.1.0dev20241126

**Comment by tle4336** [comment]
@xadupre Thank you very much for your input. Regarding the installation of onnxscript: I used Pycharm as my IDE, and I install onnxscript via `poetry install`. Which version of onnxscript and onnxruntime are you using to make it work? Because I tried it with even a simple example like the following and still incur the `Runtime Error` like above. But when I tried the same script in another environment, it works. So that puzzled me quite a bit. But I will run the above code again with the `dtype=np.float32` and let you know if the same issue still occurs. Something more subtle than missing the `dtype=np.float32` is what I feel like missing/going awry.

From that same environment with the same script above with `python run mypy`, I encountered another errors like `Unsupported operand type left for * [FLOAT/BOOL/INT]` and the guy from `mypy` is blaming that you guys are doing the `type exporting` incorrectly (https://github.com/python/mypy/issues/18200). Do you agree with him?

@script()
def f() -> FLOAT:
    return op.Constant(value_float=0.0)

An

**Comment by xadupre** [comment]
I used onnxscript from github, main branch. I did not check mypy. That's another topic. About opsml? I need more details. Onnxscript==1.17, you mean onnx? I don't how it is used in opset but i don't see why a more recent version would not work.

**Comment by tuanle0910** [comment]
@xadupre Thank you very much. I guess the topic related to `mypy` should be asked in `onnx` repo, rather than `onnxscript`? Also, the problem that I encountered was a bit different from the above: the above script worked well when I put it into a new fresh environment in Pycharm, while it did not work when I put it into an existing environment (even when all the package versions of `onnx`, `onnxscript`, `onnxconverter-common`, `onnxmltools` and their package dependencies matched exactly the same between two environments). When I looked more closely into the error above, I realized that this particular line ` filename = getfile(object)` under the function `def getsourcefile(object)` was shown to be `<input>`. This caused the `OSError: could not get source code`
 as above because `lines = linecache.getlines(file, module.__dict__)` resulted in empty list `[]`. Do you have any insights into why the filename was returned as `<input>` (particularly when it starts with `<` and ends with `>`)?

**Comment by tuanle0910** [comment]
@xadupre I hope your weekend went great! I'm sorry for having to touch base with you again. Just wonder if you have any idea on the root cause of the issue I described in the previous comment? I noticed that the `filename= getfile(object)` in the successful environment (i.e., the environment where the @script() for the function above worked well) was as lengthy as `<ipython-input-69-13062711b1c1>`. This led to `lines` being every lines within the function `conv` and much more, rather than the empty list as in the case of the environment where Runtime Error appears.

**Comment by xadupre** [comment]
Would it be possible to run the command line from the the terminal and not inside PyCharm? Sometimes, those editors run your script from another script to intercept the standard output and it may alter the filenames.

**Comment by gramalingam** [comment]
A quick response: I haven't had a chance to look into the details yet. But I remember not being able to use the script decorator in a REPL interpreter. The onnxscript translator needs the source, and it can't get it (as the above error messages imply). You could try putting the script function inside a python file and importing it. (Not sure about your IDE however)

**Comment by NoRaincheck** [comment]
I ran into this as well, though doing something maybe a bit crazy. I thought of essentially using the equivalent of macros in attempt to make some of onnxscript 'more expressive', and it would fail at the `inspect.getsource(func)`. 

If doing what I'm thinking is a sane idea, maybe there is a way to give the `src` code directly? (Or is there another interface where what I'm trying to do is more appropriate?)

Example code:

```py
import re

import numpy as np
import onnx
from onnxscript import STRING, script
from onnxscript import opset20 as op
from onnxscript.values import Opset

local = Opset("local", 1)


def create_simple_template_function(template: str, func_name: str = "template_function"):
    """
    Create a simple template function that demonstrates the concept.
    This version creates a basic ONNX function without complex type handling.

    Args:
        template: String template with {{variable}} placeholders
        func_name: Name for the generated function

    Returns:
        The generated function
    """
    # Find all placeholders in the template
    placeholders = re.findall(r"\{\{(\w+)\}\}", template)

    # Split the template by placeholders and filter out empty parts
    parts = re.split(r"\{\{(\w+)\}\}", template)

    # if no placeholders, just return a constant
    if not placeholders:
        func_code = f"""
@script(local, default_opset=op)
def {func_name}():
    return op.Constant(value_string={template})
"""
    # Placeholders exist, generate function with one argument per placeholder
    arglist = ", ".join([f"{ph}: STRING" for ph in placeholders])
    # Build up the StringConcat chain
    code_parts = []
    part_iter = iter(parts)
    for part in parts:
        if not part:
            continue
        if part in placeholders:
            code_parts.append(part)
        else:
            code_parts.append(f"op.Constant(value_string={repr(part)})")
    # Build nested StringConcat calls
    result_expr = code_parts[0]
    for part in code_parts[1:]:
        result_expr = f"op.StringConcat({result_expr}, {part})"
    func_code = f"""
@script(local, default_opset=op)
def {func_name}({arglist}):
    return {result_expr}
"""
    print("\n\nDEBUG: func_code:\n\n", func_code, "\n\nEND DEBUG\n\n")

    namespace = {}
    exec(func_code, {"op": op, "STRING": STRING, "script": script, "local": local}, namespace)
    return namespace[func_name]


if __name__ == "__main__":
    # generated function from above script -- run: create_simple_template_function("Hello {{name}}!", "hello_world") to see the code
    @script(local, default_opset=op)
    def hello_world(name: STRING):
        return op.StringConcat(op.StringConcat(op.Constant(value_string="Hello "), name), op.Constant(value_string="!"))

    print(hello_world(np.array(["John"])))

    # trying to create it dynamically
    print(create_simple_template_function("Hello {{name}}!", "hello_world_dynamic")(np.array(["John"])))
    print(
        onnx.printer.to_text(
            script(local, default_opset=op)(
                create_simple_template_function("Hello {{name}}!", "hello_world_dynamic")
            ).to_model_proto()
        )
    )
```
