### ISSUE TITLE
[torchlib] Bug with `aten::slice_scatter`

### ISSUE THREAD

**Issue by BowenBao** [microsoft/onnxscript#945]
Found in https://github.com/microsoft/onnx-converters-private/issues/166, affecting below models

```
        pyhpc_turbulent_kinetic_energy
        pyhpc_isoneutral_mixing
        MBartForConditionalGeneration
        ghostnet_100
        BartForConditionalGeneration
        eca_halonext26ts
        PLBartForConditionalGeneration
```

Minimized repro seems to be pointing to a bug with `aten::slice_scatter` torchlib implementation.

```python
import torch
import onnxruntime

def func(x, a):
    return torch.ops.aten.slice_scatter.default(x, a, 3, 0, 9223372036854775807)

x = torch.randn(8, 16, 112, 122)
a = torch.randn(8, 16, 112, 122)


func(x, a)
print("pt eager passed")
model = torch.onnx.dynamo_export(func, x, a).model_proto
session = onnxruntime.InferenceSession(model.SerializeToString(), providers=['CPUExecutionProvider'])
print(session.run(None, {'arg0': x.numpy(), 'arg1': a.numpy()}))
```
```
pt eager passed
2023-07-31 14:40:42.980386186 [E:onnxruntime:, sequential_executor.cc:514 ExecuteKernel] Non-zero status code returned while running ScatterElements node. Name:'_inline__aten_slice_scatter_onnxn17' Status Message: Indices vs updates dimensions differs at position=3 0 vs 122
Traceback (most recent call last):
  File "repro_scatter_slice.py", line 15, in <module>
    print(session.run(None, {'arg0': x.numpy(), 'arg1': a.numpy()}))
  File "/home/bowbao/anaconda3/envs/torch38/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 219, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running ScatterElements node. Name:'_inline__aten_slice_scatter_onnxn17' Status Message: Indices vs updates dimensions differs at position=3 0 vs 122
```

**Comment by justinchuby** [comment]
Assigning to [er3x3](https://github.com/er3x3). Thanks for creating the PR!
